### ISSUE TITLE
[Bug]: Running console ninja with tsx watch (next.js pages with custom server) makes the application re-start endlessly

### ISSUE THREAD

**Issue by GGAlanSmithee** [wallabyjs/console-ninja#377]
### What happened?

i am running a next.js pages project with a custom server. The server keeps restarting, over and over. I expected it to start once, as normal.

```sh
$ npm run dev:log

> project@0.1.0 dev:log
> console-ninja tsx watch --clear-screen=false server.ts

10:22:59 AM [tsx] change in ./lib\functions\a.ts Restarting...
10:23:04 AM [tsx] change in ./lib\functions\a.ts Restarting...
10:23:09 AM [tsx] change in ./lib\functions\a.ts Restarting...
10:23:15 AM [tsx] change in ./lib\functions\a.ts Restarting...
```

### Version

1.0.393

### CLI command to start your dev tool

`console-ninja tsx watch --clear-screen=false server.ts`

### Steps to reproduce (or sample repo)

1. Create a next.js 15 project (using pages) with a custom server, using ts
2. Start it by running `console-ninja tsx watch --clear-screen=false server.ts`

There might be more too it, because my project is several 100 files large, i run cronjobs, websockets, etc, so there is a lot of complexity that might potentially pay into this. Having said that, running `console-ninja tsx` _without_ `watch` works.

### Log output

```shell
10:04:03.871 info buildHook-10504 updating build hook tool
10:04:03.885 ERR! host unable to set access and modified time for file c:\projects\project\components\a.tsx
10:04:03.989 info host client disconnected: buildHook 1006
10:04:03.989 info host client disconnected: buildHook 1006, has clients true
10:04:03.989 info host client disconnected: buildHook 1006
10:04:03.989 info host client disconnected: buildHook 1006, has clients true
10:04:03.989 info host client disconnected: runtimeHook 1006
10:04:03.989 info host client disconnected: runtimeHook
10:04:03.989 info host client disconnected: runtimeHook 1006
10:04:03.989 info host client disconnected: runtimeHook
10:04:03.989 info host client disconnected: runtimeHook 1006
10:04:03.989 info host client disconnected: runtimeHook
10:04:03.989 info host client disconnected: runtimeHook 1006
10:04:03.989 info host client disconnected: runtimeHook
10:04:04.211 info buildHook-11112 installing build hook for node at c:\projects\project, node v20.12.2
10:04:04.227 info buildHook-11112 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:04:04.227 info buildHook-11112 running tools: node
10:04:04.228 info buildHook-11112 installing fs interceptor
10:04:04.303 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:04.312 info host client connected: buildHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:04.325 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.336 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.355 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:04.361 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.390 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.395 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.414 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:04.428 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.432 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.446 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.455 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.462 info buildHook-11112 file processed (stat): 9 log points, error handler: false, network logging handler: false
10:04:04.483 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.501 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.513 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.533 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.547 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.561 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.568 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.601 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:04.625 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.631 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.644 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.650 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.654 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.660 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.664 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.668 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.674 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.684 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.706 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.709 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:04.714 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:04.725 info buildHook-11112 file processed (stat): 0 log points, error handler: false, network logging handler: false
10:04:04.733 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:04.744 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:04.758 info buildHook-11112 file processed (stat): 27 log points, error handler: false, network logging handler: false
10:04:04.766 info buildHook-11112 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:04:04.766 info buildHook-11112 running tools: node
10:04:04.832 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:04.832 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:05.046 info buildHook-11112 installing build hook for node at c:\projects\project, node v20.12.2
10:04:05.061 info buildHook-11112 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:04:05.061 info buildHook-11112 running tools: node
10:04:05.063 info buildHook-11112 installing fs interceptor
10:04:05.095 info host client connected: buildHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:05.126 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:05.133 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.138 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.147 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:05.150 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.162 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.166 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.184 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:05.196 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.201 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.213 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.222 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.228 info buildHook-11112 file processed (stat): 9 log points, error handler: false, network logging handler: false
10:04:05.246 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.261 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.271 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.297 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.312 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.323 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.329 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.359 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:05.378 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.383 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.395 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.399 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.403 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.406 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.409 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.413 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.418 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.426 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.444 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.447 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:05.451 info buildHook-11112 file processed (stat): 1 log points, error handler: false, network logging handler: false
10:04:05.461 info buildHook-11112 file processed (stat): 0 log points, error handler: false, network logging handler: false
10:04:05.467 info buildHook-11112 file processed (stat): 2 log points, error handler: false, network logging handler: false
10:04:05.476 info buildHook-11112 file processed (stat): 3 log points, error handler: false, network logging handler: false
10:04:05.488 info buildHook-11112 file processed (stat): 27 log points, error handler: false, network logging handler: false
10:04:05.497 info buildHook-11112 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:04:05.497 info buildHook-11112 running tools: node
10:04:05.531 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:05.532 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 61383 }
10:04:08.234 info host client disconnected: buildHook 1006
10:04:08.235 info host client disconnected: buildHook 1006, has clients true
10:04:08.235 info host client disconnected: runtimeHook 1006
10:04:08.235 info host client disconnected: runtimeHook
10:04:08.235 info host client disconnected: runtimeHook 1006
10:04:08.235 info host client disconnected: runtimeHook
10:04:08.235 info host client disconnected: buildHook 1006
10:04:08.235 info host client disconnected: buildHook 1006, has clients true
10:04:08.235 info host client disconnected: runtimeHook 1006
10:04:08.235 info host client disconnected: runtimeHook
10:04:08.235 info host client disconnected: runtimeHook 1006
10:04:08.235 info host client disconnected: runtimeHook
10:04:08.264 info host client disconnected: runtimeHook 1006
10:04:08.265 info host client disconnected: runtimeHook
10:04:08.265 info host client disconnected: runtimeHook 1006
10:04:08.265 info host client disconnected: runtimeHook
10:04:08.265 info host client disconnected: buildHook 4100
10:04:08.265 info host client disconnected: buildHook 4100, has clients false
```

**Comment by GGAlanSmithee** [comment]
I understand this might be hard to track down given the information I provided, but that's what I have to share. I will try to create a simple reproduction, but not sure that I will be able too. But let me know if there's something else that I can do to help track this down.

**Comment by GGAlanSmithee** [comment]
I also see some logs concerning som files that does not exist any more, and that is not referenced from anywhere, so might be something is cached 🤔

**Comment by GGAlanSmithee** [comment]
I tried doing a cleanup routine, but the problem persists

* delete `node_modules`
* delete `.next`
* delete `package-lock.json`
* run `npm cache clean -p`
* run `npm i`

What I did find though is that if I do this

* `Console Ninja: Pause`
* `console-ninja npx tsx watch ./server`
* `Console Ninja: Start`

it actually seems to work, so it might be something related to the startup process

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. While we haven't been able to reproduce the exact issue with endless restarts, we have identified an issue that may have been affecting your scenario. We have fixed the suspected issue and released the fix in v1.0.395. Please try updating Ninja extension, restart `console-ninja npx tsx watch ...` and let us know if it's fixed for you.

**Comment by GGAlanSmithee** [comment]
Thanks for looking into this @ArtemGovorov . Unfortunately the issue persists. The one error that sticks out is this

> 10:38:50.689 ERR! host unable to set access and modified time for file

I will see if I can create a simpler reproduction

**Comment by GGAlanSmithee** [comment]
Actually, I was able to reproduce this with a 100% vanilla next.js pages project with a custom server, so it's interesting that you could not reproduce it, then it might have something to do with my machine 🤔 

Anyhow, here's a reproduction: https://github.com/GGAlanSmithee/console-ninja-tsx-repro

Just run `npm i` and `npm run dev` and you will see that it restarts over and over.

 I am using node `v22.9.0` btw.

**Comment by ArtemGovorov** [comment]
@GGAlanSmithee Thanks for sharing the sample repo. We have been able to reproduce and identify the issue and have released the fix. Please update to v1.0.397, restart `console-ninja npx tsx watch...` and let us know if it works for you with the fix.

**Comment by GGAlanSmithee** [comment]
Yes, works, thanks for the quick help @ArtemGovorov 🙏🏼
